name: Build GDC

on: [push, pull_request]

jobs:
  build-release:
    name: Build GDC
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    env:
      TARGET_VERSION: '11.2.0'
    steps:
      - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2
        with:
          install: gcc make base-devel git gmp mpfr mpc

      - name: Checkout GDC
        run: git clone --branch=releases/gcc-$TARGET_VERSION --depth=1 git://gcc.gnu.org/git/gcc.git

      - name: Configure
        run: |
          mkdir gcc-build
          cd gcc-build
          ../gcc/configure \
            --prefix=/mingw64 \
            --build=x86_64-w64-mingw32 \
            --host=x86_64-w64-mingw32 \
            --target=x86_64-w64-mingw32 \
            --disable-bootstrap \
            --disable-werror \
            --disable-libssp \
            --disable-libgomp \
            --disable-libmudflap \
            --disable-libquadmath \
            --disable-libitm  \
            --disable-libsanitizer \
            --disable-libstdcxx-pch \
            --with-arch=x86-64 \
            --with-gnu-as \
            --with-gnu-ld \
            --with-gmp=/mingw64 \
            --with-mpfr=/mingw64 \
            --with-mpc=/mingw64 \
            --with-isl=/mingw64 \
            --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include \
            --libexecdir=/mingw64/lib \
            --enable-languages=d \
            --enable-libphobos \
            --enable-shared \
            --enable-static \
            --disable-multilib

      - name: Build
        run: cd gcc-build && make -j4

      - name: Copy binaries / install
        run: cd gcc-build && sudo make install

      - uses: actions/upload-artifact@v3
        with:
          name: gdc-${{env.TARGET_VERSION}}
          path: /mingw64

      - name: Test Hello World
        run: .\gdc\gdc.exe -run test.d
