name: Build GDC

on: [push, pull_request]

jobs:
  build-release:
    name: Build GDC
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    env:
      TARGET_VERSION: '12.2.0'
    steps:
      - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2
        with:
          install: gcc make base-devel git

      - name: Install Dependencies
        run: |
          sudo apt install gdc gcc-mingw-w64 mingw-w64 -y
          gdc --version

      - name: Checkout GDC
        run: git clone --branch=releases/gcc-$TARGET_VERSION --depth=1 git://gcc.gnu.org/git/gcc.git

      - name: Configure
        run: |
          cd gcc
          mkdir gcc-build
          cd gcc-build
          ../gcc/configure \
            --prefix=/mingw64 \
            --build=x86_64-w64-mingw32 \
            --host=x86_64-w64-mingw32 \
            --target=x86_64-w64-mingw32 \
            --disable-libssp \
            --with-gnu-as \
            --with-gnu-ld \
            --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include \
            --libexecdir=/mingw64/lib \
            --enable-languages=d \
            --enable-shared \
            --enable-static \
            --disable-multilib

      - name: Build
        run: cd gcc/gcc-build && make -j4

      - name: Copy binaries / install
        run: cd gcc/gcc-build && sudo make install

      - uses: actions/upload-artifact@v3
        with:
          name: gdc-${{env.TARGET_VERSION}}
          path: /mingw64

      - name: Test Hello World
        run: .\gdc\gdc.exe -run test.d
